//! Compare Rust and PyTorch with identical input data
//!
//! This example loads the same input data that was generated by Python
//! and verifies that the Rust implementation produces matching results.
//!
//! Usage:
//!     cargo run --release --example compare_exact_same_input

use candle_core::{Device, Tensor};
use std::fs;
use std::io::{Read, Write};

fn load_numpy_f32(path: &str) -> Result<Tensor, Box<dyn std::error::Error>> {
    let mut file = std::fs::File::open(path)?;
    let mut buffer = Vec::new();
    file.read_to_end(&mut buffer)?;

    // NPY format: magic (6 bytes) + version (2 bytes) + header_len (2 or 4 bytes) + header
    // For simplicity, find the first newline which ends the header
    let mut header_end = 0;
    for i in 0..buffer.len() {
        if buffer[i] == b'\n' {
            header_end = i + 1;
            break;
        }
    }

    // Ensure we have enough data
    let data_start = header_end.min(buffer.len() - 1);
    let data_bytes = &buffer[data_start..];

    // Each float32 is 4 bytes
    let expected_elements = 1 * 2880; // batch * seq_len
    let actual_elements = data_bytes.len() / 4;

    if actual_elements < expected_elements {
        return Err(format!(
            "Expected {} elements but got {} ({} bytes after header)",
            expected_elements,
            actual_elements,
            data_bytes.len()
        )
        .into());
    }

    let data: Vec<f32> = data_bytes
        .chunks_exact(4)
        .take(expected_elements)
        .map(|chunk| f32::from_le_bytes([chunk[0], chunk[1], chunk[2], chunk[3]]))
        .collect();

    Ok(Tensor::from_vec(data, (1, 2880), &Device::Cpu)?)
}

fn debug_tensor(name: &str, tensor: &Tensor) {
    let mean = tensor.mean_all().unwrap().to_scalar::<f32>().unwrap();
    let mean_sq = tensor
        .sqr()
        .unwrap()
        .mean_all()
        .unwrap()
        .to_scalar::<f32>()
        .unwrap();
    let std = (mean_sq - mean * mean).sqrt();
    let min = tensor.min_all().unwrap().to_scalar::<f32>().unwrap();
    let max = tensor.max_all().unwrap().to_scalar::<f32>().unwrap();

    println!(
        "[{}] {}: shape={:?}, mean={:.6}, std={:.6}, min={:.6}, max={:.6}",
        name,
        name,
        tensor.dims(),
        mean,
        std,
        min,
        max
    );
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!("Sundial Rust vs PyTorch - Same Input Comparison");
    println!("================================================\n");

    // Load the same input data
    println!("Loading input data from /tmp/input_data.npy...");
    let input = load_numpy_f32("/tmp/input_data.npy")?;
    debug_tensor("input", &input);

    // Load config and model
    let config = sundial_rust::SundialConfig::default();
    let device = Device::Cpu;

    println!("\nLoading Sundial model...");
    let model = sundial_rust::SundialModel::load_from_safetensors(
        config,
        "weights/model.safetensors",
        &device,
    )?;
    println!("Model loaded successfully!\n");

    // Run inference with RevIN disabled (to match Python comparison)
    println!("Running inference (revin=false)...");
    let start = std::time::Instant::now();
    let output = model.generate(&input, 14, 1, false)?;
    let elapsed = start.elapsed();

    println!("\nOutput shape: {:?}", output.dims());
    println!("Generation time: {:.2}s\n", elapsed.as_secs_f64());

    // Save output for comparison
    let mean_forecast = output.mean_keepdim(0)?.squeeze(0)?.squeeze(0)?;
    let mut file = fs::File::create("/tmp/rust_output.npy")?;
    let data: Vec<f32> = mean_forecast.flatten_all()?.to_vec1()?;
    for &val in &data {
        file.write_all(&val.to_le_bytes())?;
    }
    println!("Saved Rust output to /tmp/rust_output.npy");

    // Print statistics
    println!("\nRust output statistics:");
    debug_tensor("output", &mean_forecast);

    println!("\nFirst 14 forecast values:");
    for i in 0..14 {
        let val: f32 = mean_forecast.get(i)?.to_scalar()?;
        println!("  Step {}: {:.6}", i + 1, val);
    }

    println!("\nTo compare with Python, run:");
    println!(
        "  python3 scripts/compare_tensors.py --python /tmp/python_intermediates.npz --rust /tmp/"
    );

    Ok(())
}
